version: "3.7"
services:
  web:
    build:
      context: .
      target: dev
    env_file:
      - .env.dev
    stdin_open: true
    tty: true
    command: ./bin/start_dev_server.sh
    volumes:
      - ".:/flat-search"
      - bundle:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: "healthcheck/postgres:alpine"
    environment:
      POSTGRES_PASSWORD: db_password
volumes:
  bundle: