name: Rails
on: push

jobs:
  verify:
    name: Build and test
    env:
      DATABASE_HOST: localhost
      DATABASE_USERNAME: rails_github_actions
      DATABASE_PASSWORD: postgres
      RAILS_ENV: test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: rails_github_actions
          POSTGRES_DB: rails_github_actions_test
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.1'
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: setup test database
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate
      - name: Run tests & lint
        run: |
          bundle exec rspec 
          bundle exec rubocop
