name: Rails
on: push

jobs:
  verify:
    name: Build and test
    env:
      DATABASE_URL: postgres://postgres:@localhost:5432/test
      RAILS_ENV: test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: rails_github_actions
          POSTGRES_DB: rails_github_actions_test
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '3.1.1'
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: setup test database
        run: rails db:create && rails db:migrate
      - name: Run tests & lint
        run: rspec && rubocop
